name: artem-integrator
region: fra
services:
- name: web
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: aaatema/artem.integrator
  run_command: python webhook.py
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  envs:
  - key: TELEGRAM_BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ANTHROPIC_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ZEP_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SUPABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: SUPABASE_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DIGITALOCEAN_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: CONTEXT7_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ADMIN_USER_ID
    scope: RUN_AND_BUILD_TIME
    value: "479699775"
  - key: ADMIN_USERNAMES
    scope: RUN_AND_BUILD_TIME
    value: "aaatema"
  - key: BOT_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: "artem_integrator_bot"
  - key: BASE_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://artem-integrator-h75hq.ondigitalocean.app"
  - key: WEBHOOK_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://artem-integrator-h75hq.ondigitalocean.app/webhook"
  - key: ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: "production"
  - key: VOICE_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: MCP_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: SUPABASE_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: DIGITALOCEAN_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: CONTEXT7_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "false"