# Конфигурация паттернов для классификации намерений

intent_patterns:
  # MCP команды
  - intent: mcp_command
    confidence: 0.9
    patterns:
      - "(покажи|показать|выведи|отобрази)\\s+(все|список)?\\s*(приложен|app|apps)"
      - "(какие|что за|проверь|есть ли)\\s*(у меня)?\\s*(приложен|app|apps)"
      - "(список|list|перечень)\\s*(всех)?\\s*(приложен|app|apps)"
      - "(покажи|показать|выведи)\\s+(все|список)?\\s*(баз[ыу]?\\s*данных|database|db)"
      - "(статус|состояние|status)\\s*(приложен|деплой|баз)"
      - "деплойменты\\s*(приложен|app)?"
      - "(проверь|check)\\s*(деплой|deploy)"
      - "/mcp\\s+.*"
      - "/db\\s+.*"

  # Генерация изображений
  - intent: image_generation
    confidence: 0.95
    patterns:
      - "(нарисуй|сгенерируй|создай|сделай)\\s*.*(картин|изображен|рисун|фото|иллюстрац)"
      - "(картин|изображен|рисун|фото)\\s*(с|где|на котор|изображающ)"
      - "сгенерируй\\s*(мне)?\\s*(изображен|картин)"
      - "dall-?e\\s*.*"
      - "(визуализируй|проиллюстрируй)\\s*.*"
      - "создай\\s*(мне)?\\s*арт\\s*"

  # Анализ видео
  - intent: video_analysis  
    confidence: 0.9
    patterns:
      - "(проанализируй|анализ|посмотри|изучи)\\s*.*(видео|ролик|рилс|reels|video)"
      - "(что|о чем|про что)\\s*(это|данное)?\\s*(видео|ролик|рилс)"
      - "(видео|ролик|рилс)\\s*.*(анализ|проанализ|разбор|обзор)"
      - "(скачай|загрузи)\\s*(и)?\\s*(проанализируй)?\\s*(видео|ролик)"
      - "apify\\s*.*(видео|video|рилс)"
      - "vision\\s*.*(видео|video|анализ)"
      - "(просмотры|статистика)\\s*(видео|ролик|рилс)"

# Дополнительные ключевые слова для инструментов
tool_keywords:
  mcp_executor:
    - "digitalocean"
    - "do apps"
    - "postgresql"
    - "postgres"
    - "mysql"
    - "redis"
    - "mongodb"
    - "кластер"
    - "cluster"
    - "контейнер"
    - "container"
    - "docker"
    
  image_generator:
    - "арт"
    - "artwork"
    - "illustration"
    - "дизайн"
    - "design"
    - "стиль"
    - "style"
    - "цифровое искусство"
    - "digital art"
    
  vision_analyzer:
    - "кадр"
    - "frame"
    - "сцена"
    - "scene"
    - "контент"
    - "content"
    - "instagram"
    - "tiktok"
    - "youtube"
    - "соцсети"
    - "social media"

# Фразы для определения неоднозначности
ambiguity_indicators:
  - "или может"
  - "не знаю что выбрать"
  - "что лучше"
  - "есть варианты"
  - "можно и так и так"
  - "не уверен"
  - "наверное"
  - "возможно"