# Конфигурация паттернов для классификации намерений

intent_patterns:
  # MCP команды
  - intent: mcp_command
    confidence: 0.9
    patterns:
      - "(покажи|показать|выведи|отобрази)\\s+(все|список)?\\s*(приложен|app|apps)"
      - "(какие|что за|проверь|есть ли)\\s*(у меня)?\\s*(приложен|app|apps)"
      - "(список|list|перечень)\\s*(всех)?\\s*(приложен|app|apps)"
      - "(покажи|показать|выведи)\\s+(все|список)?\\s*(баз[ыу]?\\s*данных|database|db)"
      - "(статус|состояние|status)\\s*(приложен|деплой|баз)"
      - "деплойменты\\s*(приложен|app)?"
      - "(проверь|check)\\s*(деплой|deploy)"
      - "/mcp\\s+.*"
      - "/db\\s+.*"

  # Генерация изображений
  - intent: image_generation
    confidence: 0.95
    patterns:
      - "(нарисуй|сгенерируй|создай|сделай)\\s*.*(картин|изображен|рисун|фото|иллюстрац)"
      - "(картин|изображен|рисун|фото)\\s*(с|где|на котор|изображающ)"
      - "сгенерируй\\s*(мне)?\\s*(изображен|картин)"
      - "dall-?e\\s*.*"
      - "(визуализируй|проиллюстрируй)\\s*.*"
      - "создай\\s*(мне)?\\s*арт\\s*"

  # Анализ YouTube видео
  - intent: youtube_analysis  
    confidence: 0.9
    patterns:
      - "(проанализируй|анализ|посмотри|изучи)\\s*.*(youtube|ютуб|видео)"
      - "youtube\\.com/watch\\?v="
      - "youtu\\.be/"
      - "(что|о чем|про что)\\s*(это|данное)?\\s*(видео|ролик).*youtube"
      - "(субтитры|subtitles|транскрипц)\\s*(видео|ролик|youtube)"
      - "(получи|извлеки|достань)\\s*(субтитры|текст)\\s*(из)?\\s*(видео|youtube)"
      - "(статистика|просмотры|лайки)\\s*(видео|youtube|ютуб)"
      - "youtube\\s*(видео|ролик)?\\s*(анализ|информац)"

# Дополнительные ключевые слова для инструментов
tool_keywords:
  mcp_executor:
    - "digitalocean"
    - "do apps"
    - "postgresql"
    - "postgres"
    - "mysql"
    - "redis"
    - "mongodb"
    - "кластер"
    - "cluster"
    - "контейнер"
    - "container"
    - "docker"
    
  image_generator:
    - "арт"
    - "artwork"
    - "illustration"
    - "дизайн"
    - "design"
    - "стиль"
    - "style"
    - "цифровое искусство"
    - "digital art"
    
  youtube_analyzer:
    - "youtube"
    - "ютуб"
    - "видео"
    - "video"
    - "субтитры"
    - "subtitles"
    - "транскрипция"
    - "transcription"
    - "просмотры"
    - "views"
    - "лайки"
    - "likes"
    - "канал"
    - "channel"

# Фразы для определения неоднозначности
ambiguity_indicators:
  - "или может"
  - "не знаю что выбрать"
  - "что лучше"
  - "есть варианты"
  - "можно и так и так"
  - "не уверен"
  - "наверное"
  - "возможно"