[global]
# dataFrameSerialization удален - больше не поддерживается в Streamlit 1.28+

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost" 
gatherUsageStats = false
