# Streamlit Secrets Configuration
# GitHub API Configuration
GITHUB_TOKEN = "your_github_token_here"
GITHUB_OWNER = "Timosan61"
GITHUB_REPO = "artem.integrator"

# Railway Configuration
RAILWAY_TOKEN = "your_railway_token_here"
RAILWAY_PROJECT_ID = "your_railway_project_id_here"
RAILWAY_SERVICE_ID = "your_railway_service_id_here"

# Admin Configuration
ADMIN_PASSWORD = "your_admin_password_here"

# Bot Configuration for Streamlit Cloud
TELEGRAM_BOT_TOKEN = "dummy:token_for_streamlit_cloud"
BOT_USERNAME = "artem_integrator_bot"
ADMIN_USER_ID = ""
ADMIN_USERNAMES = ""
OPENAI_API_KEY = ""
ANTHROPIC_API_KEY = ""
ZEP_API_KEY = ""
BASE_URL = "https://artem-integrator.streamlit.app"
TELEGRAM_WEBHOOK_SECRET = "streamlit-secret"
VOICE_ENABLED = "false"
MCP_ENABLED = "false"
ENVIRONMENT = "streamlit_cloud"
DEBUG = "false"
PORT = "8501"
MAX_MESSAGE_LENGTH = "4096"