# Streamlit Secrets Configuration
# GitHub API Configuration
GITHUB_TOKEN = "your_github_token_here"
GITHUB_OWNER = "Timosan61"
GITHUB_REPO = "artem.integrator"

# Railway Configuration
RAILWAY_TOKEN = "your_railway_token_here"
RAILWAY_PROJECT_ID = "your_railway_project_id_here"
RAILWAY_SERVICE_ID = "your_railway_service_id_here"

# Admin Configuration
ADMIN_PASSWORD = "your_admin_password_here"